# id юзера телеграма, кому отправлять сообщения
telegram_user_id: 123456

# ключ API rutracker (написан в профиле), можно не указывать, тогда количество запросов будет сильно ограничено
api_key:

# Токен бота телеграм, отправителя сообщений. Если пусто, то писать будет https://t.me/PalnB_bot (бот не умеет писать первым, ему нужно что-то отправить, чтобы он смог отправлять сообщения)
bot_token: